[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
[project]
name = "giskard_cicd"
readme = "README.md"
dependencies = [
    "datasets",
    "giskard >= 2.1.0",
    "huggingface_hub",
    "torch",
    "transformers",
]
requires-python = ">=3.9"
