detectors:
  - ethical_bias
  - text_perturbation
  - robustness
  - performance
  - underconfidence
  - overconfidence
  - spurious_correlation

configuration:
  ethical_bias:
    threshold:
      0.01

inference_type: hf_pipeline